services:
  op-bridge-ui:
    container_name: op-bridge-ui
    image: snapchain/op-bridge-ui:v0.1.0
    ports:
      - "3002:3000"
    entrypoint:
      - "/bin/sh"
      - "/entrypoint.sh"
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_L1_CHAIN_ID=${NEXT_PUBLIC_L1_CHAIN_ID}
      - NEXT_PUBLIC_L1_CHAIN_NAME=${NEXT_PUBLIC_L1_CHAIN_NAME}
      - NEXT_PUBLIC_L1_RPC_URL=${NEXT_PUBLIC_L1_RPC_URL}
      - NEXT_PUBLIC_L1_EXPLORER_URL=${NEXT_PUBLIC_L1_EXPLORER_URL}
      - NEXT_PUBLIC_L2_CHAIN_ID=${NEXT_PUBLIC_L2_CHAIN_ID}
      - NEXT_PUBLIC_L2_CHAIN_NAME=${NEXT_PUBLIC_L2_CHAIN_NAME}
      - NEXT_PUBLIC_L2_RPC_URL=${NEXT_PUBLIC_L2_RPC_URL}
      - NEXT_PUBLIC_L2_EXPLORER_URL=${NEXT_PUBLIC_L2_EXPLORER_URL}
      - NEXT_PUBLIC_L1_STANDARD_BRIDGE_PROXY=${NEXT_PUBLIC_L1_STANDARD_BRIDGE_PROXY}
      - NEXT_PUBLIC_L1_OPTIMISM_PORTAL_PROXY=${NEXT_PUBLIC_L1_OPTIMISM_PORTAL_PROXY}
      - NEXT_PUBLIC_L2_STANDARD_BRIDGE_PROXY=${NEXT_PUBLIC_L2_STANDARD_BRIDGE_PROXY}
      - NEXT_PUBLIC_DISPUTE_GAME_FACTORY_PROXY=${NEXT_PUBLIC_DISPUTE_GAME_FACTORY_PROXY}
      - NEXT_PUBLIC_L2_OUTPUT_ORACLE_PROXY=${NEXT_PUBLIC_L2_OUTPUT_ORACLE_PROXY}
      - NEXT_PUBLIC_L1_MULTICALL3_ADDRESS=${NEXT_PUBLIC_L1_MULTICALL3_ADDRESS}